### ISSUE TITLE
url validation has problems

### ISSUE THREAD

**Issue by hubo0831** [redcodemohammed/vue-sounds#1]
let urlRegEx = /https?:\/\/(www\.)?[-a-zA-Z0-9\@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()\@:%_\+.~#?&//=]*)/gi;
    if (typeof url !== "string" || url.length <= 0 || !urlRegEx.test(url)) {
        throw new Error("Invalid url");
    }

please change it,  "/a/b.ogg" or "http://localhost/a/b.ogg" should be valid, thanks!

**Comment by redcodemohammed** [comment]
@hubo0831 
Do you think this one will be good?
`
(https?:\/\/(www.)?[-a-zA-Z0-9@:%.+~#=]{1,256}.[a-zA-Z0-9()]{1,6}\b)?([-a-zA-Z0-9()@:%+.~#?&//=]*)
`

**Comment by hubo0831** [comment]
I think url is not null or empty is good, let caller decide url is valid
